name: Continuous Deploy # action名称

on: # 在push代码的时候运行此action
  push:
    branches:
      - main
      - master

jobs:
  auto_deploy_job:
    name: build-deploy

    runs-on: ubuntu-latest # 运行环境，最新ubuntu

    steps:
      - name: excute command # 更新代码和重启
        uses: garygrossgarten/github-action-ssh@release # 使用第三方action 远程执行命令
        with:
          command: cd /root/project/journey/journey-server && git checkout . && git pull && yarn && yarn re-start
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
